# Generated by Django 4.1.2 on 2022-10-15 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_auto_20210322_2234"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task", name="title", field=models.CharField(max_length=500),
        ),
    ]
