# Generated by Django 4.1.2 on 2022-10-15 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_alter_task_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task", name="title", field=models.CharField(max_length=200),
        ),
    ]
