# Generated by Django 4.1.2 on 2022-10-15 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_alter_task_title"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task", old_name="done", new_name="done",
        ),
    ]
