# Generated by Django 4.1.2 on 2022-10-16 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_alter_task_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="task", name="deadline", field=models.DateTimeField(null=True),
        ),
    ]
